# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XML_PBR_new <- function(beam_spot_grid, fluenceMatrix) {
    .Call('HITXML_XML_PBR_new', PACKAGE = 'HITXML', beam_spot_grid, fluenceMatrix)
}

