// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// XML_PBR_new
NumericVector XML_PBR_new(DataFrame beam_spot_grid, NumericMatrix fluenceMatrix);
RcppExport SEXP HITXML_XML_PBR_new(SEXP beam_spot_gridSEXP, SEXP fluenceMatrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type beam_spot_grid(beam_spot_gridSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type fluenceMatrix(fluenceMatrixSEXP);
    __result = Rcpp::wrap(XML_PBR_new(beam_spot_grid, fluenceMatrix));
    return __result;
END_RCPP
}
